# Generated by Django 5.1.1 on 2025-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
