# Generated by Django 3.2.25 on 2025-01-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20250106_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproduct',
            name='product_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gamemoneyproduct',
            name='product_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='product_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accountproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gamemoneyproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
