# Generated by Django 3.2.25 on 2025-01-07 05:10

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20250107_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountproduct',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='gamemoneyproduct',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='itemproduct',
            name='product_image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcut_image', models.ImageField(upload_to=items.models.product_image_upload_path)),
                ('account_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.accountproduct')),
                ('game_money_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.gamemoneyproduct')),
                ('item_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemproduct')),
            ],
        ),
    ]
