# Generated by Django 5.1.1 on 2025-01-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_purchaserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserecord',
            name='product_type',
            field=models.CharField(max_length=20),
        ),
    ]
