# Generated by Django 5.1.1 on 2025-01-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20250107_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='prodcut_image',
            new_name='product_image',
        ),
    ]
