# Generated by Django 5.1.1 on 2025-01-08 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_prodcut_image_productimage_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='account_product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='items.accountproduct'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='game_money_product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='items.gamemoneyproduct'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='item_product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemproduct'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
