# Generated by Django 5.1.1 on 2025-01-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_productimage_account_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='account_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.accountproduct'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='game_money_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.gamemoneyproduct'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='item_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemproduct'),
        ),
    ]
